baseURL = "https://example.com"
languageCode = "en"
DefaultContentLanguage = "pt-br"
title = "Daniel S. Debastiani"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Daniel S. Debastiani"
author = "Daniel S. Debastiani"
description = "Consultor Desenvolvedor de Software | Desenvolvedor Android"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = []

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/dsdebastiani"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/dsdebastiani/"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  # [[menu.main]]
  # name = "Posts"
  # weight = 200
  # identifier = "posts"
  # url = "/post/"
  #
  # [[menu.main]]
  # name = "About"
  # weight = 300
  # identifier = "about"
  # url = "/about/"
